POST http://localhost:3003/users/create
Content-Type: application/json

{
    "name": "Joaquim Silveira",
    "cpf": "111.111.111-12",
    "birthDate": "10/02/1995"
}

###

GET http://localhost:3003/users/
Content-Type: application/json

###

GET http://localhost:3003/user
Content-Type: application/json

{
    "name": "João Siqueira",
    "cpf": "111.111.111-11"
}

###

PUT http://localhost:3003/user/transfer
Content-Type: application/json

{
    "name": "João Siqueira",
    "cpf": "111.111.111-11",
    "value": 23
}